package com.tcrade.constants;

import lombok.NoArgsConstructor;

import java.util.HashMap;
import java.util.Map;

import static lombok.AccessLevel.PRIVATE;

@NoArgsConstructor(access = PRIVATE)
public class Ta4jClassMapping {

    public static final Map<String, String> RULE_CLASS_MAPPING = new HashMap<>();
    public static final Map<String, String> INDICATOR_CLASS_MAPPING = new HashMap<>();

    private static final String RULES_BASE_PATH = "org.ta4j.core.rules.";
    private static final String INDICATORS_BASE_PATH = "org.ta4j.core.indicators.";
    private static final String INDICATORS_ADX_PATH = INDICATORS_BASE_PATH + "adx.";
    private static final String INDICATORS_BOLLINGER_PATH = INDICATORS_BASE_PATH + "bollinger.";
    private static final String INDICATORS_CANDLES_PATH = INDICATORS_BASE_PATH + "candles.";
    private static final String INDICATORS_HELPERS_PATH = INDICATORS_BASE_PATH + "helpers.";
    private static final String INDICATORS_ICHIMOKU_PATH = INDICATORS_BASE_PATH + "ichimoku.";
    private static final String INDICATORS_KELTNER_PATH = INDICATORS_BASE_PATH + "keltner.";
    private static final String INDICATORS_PIVOTPOINTS_PATH = INDICATORS_BASE_PATH + "pivotpoints.";
    private static final String INDICATORS_STATISTICS_PATH = INDICATORS_BASE_PATH + "statistics.";
    private static final String INDICATORS_VOLUME_PATH = INDICATORS_BASE_PATH + "volume.";

    static {
        RULE_CLASS_MAPPING.put("AbstractRule", RULES_BASE_PATH + "AbstractRule");
        RULE_CLASS_MAPPING.put("AndRule", RULES_BASE_PATH + "AndRule");
        RULE_CLASS_MAPPING.put("BooleanIndicatorRule", RULES_BASE_PATH + "BooleanIndicatorRule");
        RULE_CLASS_MAPPING.put("BooleanRule", RULES_BASE_PATH + "BooleanRule");
        RULE_CLASS_MAPPING.put("ChainRule", RULES_BASE_PATH + "ChainRule");
        RULE_CLASS_MAPPING.put("CrossedDownIndicatorRule", RULES_BASE_PATH + "CrossedDownIndicatorRule");
        RULE_CLASS_MAPPING.put("CrossedUpIndicatorRule", RULES_BASE_PATH + "CrossedUpIndicatorRule");
        RULE_CLASS_MAPPING.put("DayOfWeekRule", RULES_BASE_PATH + "DayOfWeekRule");
        RULE_CLASS_MAPPING.put("FixedRule", RULES_BASE_PATH + "FixedRule");
        RULE_CLASS_MAPPING.put("InPipeRule", RULES_BASE_PATH + "InPipeRule");
        RULE_CLASS_MAPPING.put("InSlopeRule", RULES_BASE_PATH + "InSlopeRule");
        RULE_CLASS_MAPPING.put("IsEqualRule", RULES_BASE_PATH + "IsEqualRule");
        RULE_CLASS_MAPPING.put("IsFallingRule", RULES_BASE_PATH + "IsFallingRule");
        RULE_CLASS_MAPPING.put("IsHighestRule", RULES_BASE_PATH + "IsHighestRule");
        RULE_CLASS_MAPPING.put("IsLowestRule", RULES_BASE_PATH + "IsLowestRule");
        RULE_CLASS_MAPPING.put("IsRisingRule", RULES_BASE_PATH + "IsRisingRule");
        RULE_CLASS_MAPPING.put("JustOnceRule", RULES_BASE_PATH + "JustOnceRule");
        RULE_CLASS_MAPPING.put("NotRule", RULES_BASE_PATH + "NotRule");
        RULE_CLASS_MAPPING.put("OpenedPositionMinimumBarCountRule", RULES_BASE_PATH + "OpenedPositionMinimumBarCountRule");
        RULE_CLASS_MAPPING.put("OrRule", RULES_BASE_PATH + "OrRule");
        RULE_CLASS_MAPPING.put("OverIndicatorRule", RULES_BASE_PATH + "OverIndicatorRule");
        RULE_CLASS_MAPPING.put("StopGainRule", RULES_BASE_PATH + "StopGainRule");
        RULE_CLASS_MAPPING.put("StopLossRule", RULES_BASE_PATH + "StopLossRule");
        RULE_CLASS_MAPPING.put("TimeRangeRule", RULES_BASE_PATH + "TimeRangeRule");
        RULE_CLASS_MAPPING.put("TrailingStopLossRule", RULES_BASE_PATH + "TrailingStopLossRule");
        RULE_CLASS_MAPPING.put("UnderIndicatorRule", RULES_BASE_PATH + "UnderIndicatorRule");
        RULE_CLASS_MAPPING.put("WaitForRule", RULES_BASE_PATH + "WaitForRule");
        RULE_CLASS_MAPPING.put("XorRule", RULES_BASE_PATH + "XorRule");

        INDICATOR_CLASS_MAPPING.put("ATRIndicator", INDICATORS_BASE_PATH + "ATRIndicator");
        INDICATOR_CLASS_MAPPING.put("AbstractEMAIndicator", INDICATORS_BASE_PATH + "AbstractEMAIndicator");
        INDICATOR_CLASS_MAPPING.put("AbstractIndicator", INDICATORS_BASE_PATH + "AbstractIndicator");
        INDICATOR_CLASS_MAPPING.put("AccelerationDecelerationIndicator", INDICATORS_BASE_PATH + "AccelerationDecelerationIndicator");
        INDICATOR_CLASS_MAPPING.put("AroonDownIndicator", INDICATORS_BASE_PATH + "AroonDownIndicator");
        INDICATOR_CLASS_MAPPING.put("AroonOscillatorIndicator", INDICATORS_BASE_PATH + "AroonOscillatorIndicator");
        INDICATOR_CLASS_MAPPING.put("AroonUpIndicator", INDICATORS_BASE_PATH + "AroonUpIndicator");
        INDICATOR_CLASS_MAPPING.put("AwesomeOscillatorIndicator", INDICATORS_BASE_PATH + "AwesomeOscillatorIndicator");
        INDICATOR_CLASS_MAPPING.put("CCIIndicator", INDICATORS_BASE_PATH + "CCIIndicator");
        INDICATOR_CLASS_MAPPING.put("CMOIndicator", INDICATORS_BASE_PATH + "CMOIndicator");
        INDICATOR_CLASS_MAPPING.put("CachedIndicator", INDICATORS_BASE_PATH + "CachedIndicator");
        INDICATOR_CLASS_MAPPING.put("ChandelierExitLongIndicator", INDICATORS_BASE_PATH + "ChandelierExitLongIndicator");
        INDICATOR_CLASS_MAPPING.put("ChandelierExitShortIndicator", INDICATORS_BASE_PATH + "ChandelierExitShortIndicator");
        INDICATOR_CLASS_MAPPING.put("ChopIndicator", INDICATORS_BASE_PATH + "ChopIndicator");
        INDICATOR_CLASS_MAPPING.put("CoppockCurveIndicator", INDICATORS_BASE_PATH + "CoppockCurveIndicator");
        INDICATOR_CLASS_MAPPING.put("DPOIndicator", INDICATORS_BASE_PATH + "DPOIndicator");
        INDICATOR_CLASS_MAPPING.put("DateTimeIndicator", INDICATORS_BASE_PATH + "DateTimeIndicator");
        INDICATOR_CLASS_MAPPING.put("DistanceFromMAIndicator", INDICATORS_BASE_PATH + "DistanceFromMAIndicator");
        INDICATOR_CLASS_MAPPING.put("DoubleEMAIndicator", INDICATORS_BASE_PATH + "DoubleEMAIndicator");
        INDICATOR_CLASS_MAPPING.put("EMAIndicator", INDICATORS_BASE_PATH + "EMAIndicator");
        INDICATOR_CLASS_MAPPING.put("FisherIndicator", INDICATORS_BASE_PATH + "FisherIndicator");
        INDICATOR_CLASS_MAPPING.put("HMAIndicator", INDICATORS_BASE_PATH + "HMAIndicator");
        INDICATOR_CLASS_MAPPING.put("KAMAIndicator", INDICATORS_BASE_PATH + "KAMAIndicator");
        INDICATOR_CLASS_MAPPING.put("KSTIndicator", INDICATORS_BASE_PATH + "KSTIndicator");
        INDICATOR_CLASS_MAPPING.put("LWMAIndicator", INDICATORS_BASE_PATH + "LWMAIndicator");
        INDICATOR_CLASS_MAPPING.put("MACDIndicator", INDICATORS_BASE_PATH + "MACDIndicator");
        INDICATOR_CLASS_MAPPING.put("MMAIndicator", INDICATORS_BASE_PATH + "MMAIndicator");
        INDICATOR_CLASS_MAPPING.put("MassIndexIndicator", INDICATORS_BASE_PATH + "MassIndexIndicator");
        INDICATOR_CLASS_MAPPING.put("PPOIndicator", INDICATORS_BASE_PATH + "PPOIndicator");
        INDICATOR_CLASS_MAPPING.put("PVOIndicator", INDICATORS_BASE_PATH + "PVOIndicator");
        INDICATOR_CLASS_MAPPING.put("ParabolicSarIndicator", INDICATORS_BASE_PATH + "ParabolicSarIndicator");
        INDICATOR_CLASS_MAPPING.put("RAVIIndicator", INDICATORS_BASE_PATH + "RAVIIndicator");
        INDICATOR_CLASS_MAPPING.put("ROCIndicator", INDICATORS_BASE_PATH + "ROCIndicator");
        INDICATOR_CLASS_MAPPING.put("RSIIndicator", INDICATORS_BASE_PATH + "RSIIndicator");
        INDICATOR_CLASS_MAPPING.put("RWIHighIndicator", INDICATORS_BASE_PATH + "RWIHighIndicator");
        INDICATOR_CLASS_MAPPING.put("RWILowIndicator", INDICATORS_BASE_PATH + "RWILowIndicator");
        INDICATOR_CLASS_MAPPING.put("RecursiveCachedIndicator", INDICATORS_BASE_PATH + "RecursiveCachedIndicator");
        INDICATOR_CLASS_MAPPING.put("SMAIndicator", INDICATORS_BASE_PATH + "SMAIndicator");
        INDICATOR_CLASS_MAPPING.put("StochasticOscillatorDIndicator", INDICATORS_BASE_PATH + "StochasticOscillatorDIndicator");
        INDICATOR_CLASS_MAPPING.put("StochasticOscillatorKIndicator", INDICATORS_BASE_PATH + "StochasticOscillatorKIndicator");
        INDICATOR_CLASS_MAPPING.put("StochasticRSIIndicator", INDICATORS_BASE_PATH + "StochasticRSIIndicator");
        INDICATOR_CLASS_MAPPING.put("TripleEMAIndicator", INDICATORS_BASE_PATH + "TripleEMAIndicator");
        INDICATOR_CLASS_MAPPING.put("UlcerIndexIndicator", INDICATORS_BASE_PATH + "UlcerIndexIndicator");
        INDICATOR_CLASS_MAPPING.put("UnstableIndicator", INDICATORS_BASE_PATH + "UnstableIndicator");
        INDICATOR_CLASS_MAPPING.put("WMAIndicator", INDICATORS_BASE_PATH + "WMAIndicator");
        INDICATOR_CLASS_MAPPING.put("WilliamsRIndicator", INDICATORS_BASE_PATH + "WilliamsRIndicator");
        INDICATOR_CLASS_MAPPING.put("ZLEMAIndicator", INDICATORS_BASE_PATH + "ZLEMAIndicator");
        INDICATOR_CLASS_MAPPING.put("ADXIndicator", INDICATORS_ADX_PATH + "ADXIndicator");
        INDICATOR_CLASS_MAPPING.put("MinusDIIndicator", INDICATORS_ADX_PATH + "MinusDIIndicator");
        INDICATOR_CLASS_MAPPING.put("PlusDIIndicator", INDICATORS_ADX_PATH + "PlusDIIndicator");
        INDICATOR_CLASS_MAPPING.put("BollingerBandWidthIndicator", INDICATORS_BOLLINGER_PATH + "BollingerBandWidthIndicator");
        INDICATOR_CLASS_MAPPING.put("BollingerBandsLowerIndicator", INDICATORS_BOLLINGER_PATH + "BollingerBandsLowerIndicator");
        INDICATOR_CLASS_MAPPING.put("BollingerBandsMiddleIndicator", INDICATORS_BOLLINGER_PATH + "BollingerBandsMiddleIndicator");
        INDICATOR_CLASS_MAPPING.put("BollingerBandsUpperIndicator", INDICATORS_BOLLINGER_PATH + "BollingerBandsUpperIndicator");
        INDICATOR_CLASS_MAPPING.put("PercentBIndicator", INDICATORS_BOLLINGER_PATH + "PercentBIndicator");
        INDICATOR_CLASS_MAPPING.put("BearishEngulfingIndicator", INDICATORS_CANDLES_PATH + "BearishEngulfingIndicator");
        INDICATOR_CLASS_MAPPING.put("BearishHaramiIndicator", INDICATORS_CANDLES_PATH + "BearishHaramiIndicator");
        INDICATOR_CLASS_MAPPING.put("BullishEngulfingIndicator", INDICATORS_CANDLES_PATH + "BullishEngulfingIndicator");
        INDICATOR_CLASS_MAPPING.put("BullishHaramiIndicator", INDICATORS_CANDLES_PATH + "BullishHaramiIndicator");
        INDICATOR_CLASS_MAPPING.put("DojiIndicator", INDICATORS_CANDLES_PATH + "DojiIndicator");
        INDICATOR_CLASS_MAPPING.put("LowerShadowIndicator", INDICATORS_CANDLES_PATH + "LowerShadowIndicator");
        INDICATOR_CLASS_MAPPING.put("RealBodyIndicator", INDICATORS_CANDLES_PATH + "RealBodyIndicator");
        INDICATOR_CLASS_MAPPING.put("ThreeBlackCrowsIndicator", INDICATORS_CANDLES_PATH + "ThreeBlackCrowsIndicator");
        INDICATOR_CLASS_MAPPING.put("ThreeWhiteSoldiersIndicator", INDICATORS_CANDLES_PATH + "ThreeWhiteSoldiersIndicator");
        INDICATOR_CLASS_MAPPING.put("UpperShadowIndicator", INDICATORS_CANDLES_PATH + "UpperShadowIndicator");
        INDICATOR_CLASS_MAPPING.put("AmountIndicator", INDICATORS_HELPERS_PATH + "AmountIndicator");
        INDICATOR_CLASS_MAPPING.put("BooleanTransformIndicator", INDICATORS_HELPERS_PATH + "BooleanTransformIndicator");
        INDICATOR_CLASS_MAPPING.put("CloseLocationValueIndicator", INDICATORS_HELPERS_PATH + "CloseLocationValueIndicator");
        INDICATOR_CLASS_MAPPING.put("ClosePriceIndicator", INDICATORS_HELPERS_PATH + "ClosePriceIndicator");
        INDICATOR_CLASS_MAPPING.put("ConstantIndicator", INDICATORS_HELPERS_PATH + "ConstantIndicator");
        INDICATOR_CLASS_MAPPING.put("ConvergenceDivergenceIndicator", INDICATORS_HELPERS_PATH + "ConvergenceDivergenceIndicator");
        INDICATOR_CLASS_MAPPING.put("CrossIndicator", INDICATORS_HELPERS_PATH + "CrossIndicator");
        INDICATOR_CLASS_MAPPING.put("DXIndicator", INDICATORS_HELPERS_PATH + "DXIndicator");
        INDICATOR_CLASS_MAPPING.put("DifferenceIndicator", INDICATORS_HELPERS_PATH + "DifferenceIndicator");
        INDICATOR_CLASS_MAPPING.put("DifferencePercentage", INDICATORS_HELPERS_PATH + "DifferencePercentage");
        INDICATOR_CLASS_MAPPING.put("FixedBooleanIndicator", INDICATORS_HELPERS_PATH + "FixedBooleanIndicator");
        INDICATOR_CLASS_MAPPING.put("FixedDecimalIndicator", INDICATORS_HELPERS_PATH + "FixedDecimalIndicator");
        INDICATOR_CLASS_MAPPING.put("FixedIndicator", INDICATORS_HELPERS_PATH + "FixedIndicator");
        INDICATOR_CLASS_MAPPING.put("GainIndicator", INDICATORS_HELPERS_PATH + "GainIndicator");
        INDICATOR_CLASS_MAPPING.put("HighPriceIndicator", INDICATORS_HELPERS_PATH + "HighPriceIndicator");
        INDICATOR_CLASS_MAPPING.put("HighestValueIndicator", INDICATORS_HELPERS_PATH + "HighestValueIndicator");
        INDICATOR_CLASS_MAPPING.put("LossIndicator", INDICATORS_HELPERS_PATH + "LossIndicator");
        INDICATOR_CLASS_MAPPING.put("LowPriceIndicator", INDICATORS_HELPERS_PATH + "LowPriceIndicator");
        INDICATOR_CLASS_MAPPING.put("LowestValueIndicator", INDICATORS_HELPERS_PATH + "LowestValueIndicator");
        INDICATOR_CLASS_MAPPING.put("MedianPriceIndicator", INDICATORS_HELPERS_PATH + "MedianPriceIndicator");
        INDICATOR_CLASS_MAPPING.put("MinusDMIndicator", INDICATORS_HELPERS_PATH + "MinusDMIndicator");
        INDICATOR_CLASS_MAPPING.put("OpenPriceIndicator", INDICATORS_HELPERS_PATH + "OpenPriceIndicator");
        INDICATOR_CLASS_MAPPING.put("PlusDMIndicator", INDICATORS_HELPERS_PATH + "PlusDMIndicator");
        INDICATOR_CLASS_MAPPING.put("PreviousValueIndicator", INDICATORS_HELPERS_PATH + "PreviousValueIndicator");
        INDICATOR_CLASS_MAPPING.put("PriceIndicator", INDICATORS_HELPERS_PATH + "PriceIndicator");
        INDICATOR_CLASS_MAPPING.put("PriceVariationIndicator", INDICATORS_HELPERS_PATH + "PriceVariationIndicator");
        INDICATOR_CLASS_MAPPING.put("SumIndicator", INDICATORS_HELPERS_PATH + "SumIndicator");
        INDICATOR_CLASS_MAPPING.put("TRIndicator", INDICATORS_HELPERS_PATH + "TRIndicator");
        INDICATOR_CLASS_MAPPING.put("TradeCountIndicator", INDICATORS_HELPERS_PATH + "TradeCountIndicator");
        INDICATOR_CLASS_MAPPING.put("TransformIndicator", INDICATORS_HELPERS_PATH + "TransformIndicator");
        INDICATOR_CLASS_MAPPING.put("TypicalPriceIndicator", INDICATORS_HELPERS_PATH + "TypicalPriceIndicator");
        INDICATOR_CLASS_MAPPING.put("VolumeIndicator", INDICATORS_HELPERS_PATH + "VolumeIndicator");
        INDICATOR_CLASS_MAPPING.put("IchimokuChikouSpanIndicator", INDICATORS_ICHIMOKU_PATH + "IchimokuChikouSpanIndicator");
        INDICATOR_CLASS_MAPPING.put("IchimokuKijunSenIndicator", INDICATORS_ICHIMOKU_PATH + "IchimokuKijunSenIndicator");
        INDICATOR_CLASS_MAPPING.put("IchimokuLineIndicator", INDICATORS_ICHIMOKU_PATH + "IchimokuLineIndicator");
        INDICATOR_CLASS_MAPPING.put("IchimokuSenkouSpanAIndicator", INDICATORS_ICHIMOKU_PATH + "IchimokuSenkouSpanAIndicator");
        INDICATOR_CLASS_MAPPING.put("IchimokuSenkouSpanBIndicator", INDICATORS_ICHIMOKU_PATH + "IchimokuSenkouSpanBIndicator");
        INDICATOR_CLASS_MAPPING.put("IchimokuTenkanSenIndicator", INDICATORS_ICHIMOKU_PATH + "IchimokuTenkanSenIndicator");
        INDICATOR_CLASS_MAPPING.put("KeltnerChannelLowerIndicator", INDICATORS_KELTNER_PATH + "KeltnerChannelLowerIndicator");
        INDICATOR_CLASS_MAPPING.put("KeltnerChannelMiddleIndicator", INDICATORS_KELTNER_PATH + "KeltnerChannelMiddleIndicator");
        INDICATOR_CLASS_MAPPING.put("KeltnerChannelUpperIndicator", INDICATORS_KELTNER_PATH + "KeltnerChannelUpperIndicator");
        INDICATOR_CLASS_MAPPING.put("DeMarkPivotPointIndicator", INDICATORS_PIVOTPOINTS_PATH + "DeMarkPivotPointIndicator");
        INDICATOR_CLASS_MAPPING.put("DeMarkReversalIndicator", INDICATORS_PIVOTPOINTS_PATH + "DeMarkReversalIndicator");
        INDICATOR_CLASS_MAPPING.put("FibonacciReversalIndicator", INDICATORS_PIVOTPOINTS_PATH + "FibonacciReversalIndicator");
        INDICATOR_CLASS_MAPPING.put("PivotLevel", INDICATORS_PIVOTPOINTS_PATH + "PivotLevel");
        INDICATOR_CLASS_MAPPING.put("PivotPointIndicator", INDICATORS_PIVOTPOINTS_PATH + "PivotPointIndicator");
        INDICATOR_CLASS_MAPPING.put("StandardReversalIndicator", INDICATORS_PIVOTPOINTS_PATH + "StandardReversalIndicator");
        INDICATOR_CLASS_MAPPING.put("TimeLevel", INDICATORS_PIVOTPOINTS_PATH + "TimeLevel");
        INDICATOR_CLASS_MAPPING.put("CorrelationCoefficientIndicator", INDICATORS_STATISTICS_PATH + "CorrelationCoefficientIndicator");
        INDICATOR_CLASS_MAPPING.put("CovarianceIndicator", INDICATORS_STATISTICS_PATH + "CovarianceIndicator");
        INDICATOR_CLASS_MAPPING.put("MeanDeviationIndicator", INDICATORS_STATISTICS_PATH + "MeanDeviationIndicator");
        INDICATOR_CLASS_MAPPING.put("PearsonCorrelationIndicator", INDICATORS_STATISTICS_PATH + "PearsonCorrelationIndicator");
        INDICATOR_CLASS_MAPPING.put("PeriodicalGrowthRateIndicator", INDICATORS_STATISTICS_PATH + "PeriodicalGrowthRateIndicator");
        INDICATOR_CLASS_MAPPING.put("SigmaIndicator", INDICATORS_STATISTICS_PATH + "SigmaIndicator");
        INDICATOR_CLASS_MAPPING.put("SimpleLinearRegressionIndicator", INDICATORS_STATISTICS_PATH + "SimpleLinearRegressionIndicator");
        INDICATOR_CLASS_MAPPING.put("StandardDeviationIndicator", INDICATORS_STATISTICS_PATH + "StandardDeviationIndicator");
        INDICATOR_CLASS_MAPPING.put("StandardErrorIndicator", INDICATORS_STATISTICS_PATH + "StandardErrorIndicator");
        INDICATOR_CLASS_MAPPING.put("VarianceIndicator", INDICATORS_STATISTICS_PATH + "VarianceIndicator");
        INDICATOR_CLASS_MAPPING.put("AccumulationDistributionIndicator", INDICATORS_VOLUME_PATH + "AccumulationDistributionIndicator");
        INDICATOR_CLASS_MAPPING.put("ChaikinMoneyFlowIndicator", INDICATORS_VOLUME_PATH + "ChaikinMoneyFlowIndicator");
        INDICATOR_CLASS_MAPPING.put("ChaikinOscillatorIndicator", INDICATORS_VOLUME_PATH + "ChaikinOscillatorIndicator");
        INDICATOR_CLASS_MAPPING.put("IIIIndicator", INDICATORS_VOLUME_PATH + "IIIIndicator");
        INDICATOR_CLASS_MAPPING.put("MVWAPIndicator", INDICATORS_VOLUME_PATH + "MVWAPIndicator");
        INDICATOR_CLASS_MAPPING.put("NVIIndicator", INDICATORS_VOLUME_PATH + "NVIIndicator");
        INDICATOR_CLASS_MAPPING.put("OnBalanceVolumeIndicator", INDICATORS_VOLUME_PATH + "OnBalanceVolumeIndicator");
        INDICATOR_CLASS_MAPPING.put("PVIIndicator", INDICATORS_VOLUME_PATH + "PVIIndicator");
        INDICATOR_CLASS_MAPPING.put("ROCVIndicator", INDICATORS_VOLUME_PATH + "ROCVIndicator");
        INDICATOR_CLASS_MAPPING.put("VWAPIndicator", INDICATORS_VOLUME_PATH + "VWAPIndicator");
    }
}
